### ISSUE TITLE
مشکل در تغییر پورت ها به 8443

### ISSUE THREAD

**Issue by ir5ghub** [Saleh-Mumtaz/Proxy-Wars#1]
سلام
وقتی پورت ها رو تغییر میدیم پنل دیگه بالا نمیاد. مشکل از کجا میتونه باشه؟

**Comment by salehMomtaz** [comment]
درود
پنل رو با دامنه و http با پورت جلوی دامنه بالا بیارید، در انتهای کار قبل بستن پنل، چک کنید لینک https بدون پورت میاد بالا یا نه بعد اگر درست بود ببندیدش و برید گام اخر، فعالسازی ufw

**Comment by ir5ghub** [comment]
ممنون اوکی شد
